#!/bin/bash

# ENVIRONMENT VARIABLES ----------------------------------
	cp /incidencias-report-service/.env.example /incidencias-report-service/.env

# MIGRATIONS -----------------------------------
	echo 'Running Migrations...'
	cd /incidencias-report-service
	composer dump-autoload
	php artisan key:generate
	php artisan migrate:fresh --force -n
	echo 'Migrations done!'

# APACHE -----------------------------------
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
exec "$@"